// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlc

import ()

type Post struct {
	ID    int32
	Title string
	Body  string
}

type User struct {
	ID       int32
	Name     string
	Email    string
	Password string
}
